[model]
plume = [-39.4, 46.2]
wind = [15, 25]
baseline = 2
source = 20
steps = 50_000
dt = 0.00001
diffusivity = 1

[model.grid]
min = [-40, 45]
max = [-38, 48]
delta = [0.05, 0.05]

[sim]
out_steps = 10
out_dir = "sim_out_1x1"

[validate]
validate_steps = 10
sensor_stream = "sensor.stream"

[environment]
wind_shift = [1, 1]
variation = 0.05

[sensors]
count = 100
interval = 100
rate = 10
mobile = 10
speed = 8
noise = 0.05

[coupling]
name = '2p5m.xc'
sim_name = 'sim'
aq_source = 'aqi'